[Dimensions]
Nx = 16
Ny = 16
Nz = 16

[Weibull]
V = 5.0
s0 = 2.0
m = 1

[Other]
file_name_prefix = "results/tt_"    # path and filename prefix for the results files
mod_nf = 1 # output : one file out of mod_nf